name: Build

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

defaults:
  run:
    working-directory: ./projects/p2_image_classifier/release

jobs:
  create-release-page:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Create release page
        uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true
          body_path: ./projects/p2_image_classifier/release/RELEASE_NOTES.txt
            

  build-and-upload-assets:
    needs: create-release-page
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: macos-12
            TARGET: macos
            CMD_BUILD: |
              pyinstaller \
                --add-binary "resources/flower_classifier_SavedModel:Resources/model" \
                --add-data "resources/label_map.json:Resources" \
                --name flower_recognizer \
                --onefile \
                cli.py
              mkdir dist/flower_recognizer_archive
              mv dist/flower_recognizer dist/flower_recognizer_archive/flower_recognizer
              ditto resources/test_images dist/flower_recognizer_archive/test_images
              cd dist/
              mv flower_recognizer_archive flower_recognizer
              ditto -c -k --keepParent flower_recognizer "flower_recognizer_built_on_macOS_12.zip"
            OUT_FILE_NAME: flower_recognizer_built_on_macOS_12.zip

          - os: windows-2022
            TARGET: windows
            CMD_BUILD: |
              pyinstaller `
                --add-binary "resources\flower_classifier_SavedModel;Resources\model" `
                --add-data "resources\label_map.json;Resources" `
                --add-data "resources\test_images;Resources\test_images" `
                --name flower_recognizer `
                cli.py
              cd dist\
              tar -cvzf "flower_recognizer_built_on_Windows_Server_2022.tar.gz" flower_recognizer
            OUT_FILE_NAME: flower_recognizer_built_on_Windows_Server_2022.tar.gz

          - os: ubuntu-22.04
            TARGET: linux
            CMD_BUILD: |
              pyinstaller \
                --add-binary "resources/flower_classifier_SavedModel:Resources/model" \
                --add-data "resources/label_map.json:Resources" \
                --add-data "resources/test_images:Resources/test_images" \
                --name flower_recognizer \
                cli.py
              cd dist/ 
              tar -cvzf "flower_recognizer_built_on_Ubuntu_22_04.tar.gz" flower_recognizer
            OUT_FILE_NAME: flower_recognizer_built_on_Ubuntu_22_04.tar.gz

    steps:
      - name: Clone this repo
        uses: actions/checkout@v3.3.0

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller on ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Upload release asset
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./projects/p2_image_classifier/release/dist/${{matrix.OUT_FILE_NAME}}


